version: '24.0.5'
services:
  web:
    build: ./stocks_products
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./stocks_products:/app
    ports:
      - 8000:8000
    env_file:
      - ./.env
  db:
    image: postgres:15.0-alpine
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER="postgres"
      - POSTGRES_PASSWORD="django_password"
      - POSTGRES_DB="django_db"
volumes:
  postgres_volume: